apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolor-cluster02
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/viniciusMenezess/web-page-deploy
    path: k8s
    targetRevision: HEAD
  destination:
    namespace: web-color
    server: https://0599bcf1-45d0-42d1-90dc-c5445bed01f3.k8s.ondigitalocean.com
  project: default
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:    
    - CreateNamespace=true 